appSetName: "multinode-appset"
projectName: "appset"
chartRepo:
  path: "appset"
  revision: "master"
kinds:
  - kind-cluster-01
labels:
  flavor-a:
    keyName: flavor-a
    keyValue: flavor-a
  flavor-b:
    keyName: flavor-b
    keyValue: flavor-b
